specVersion: 0.2.0
name: subquery-shiden
version: 1.0.0
description: Indexer for Shiden network
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108'
  # endpoint: wss://rpc.shiden.astar.network
  endpoint: ws://localhost:9944
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: BondAndStake
        - handler: handleCall
          kind: substrate/CallHandler
